# Generated by Django 5.0.6 on 2025-08-20 16:24

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_customuser_username'),
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='vehiclevariant',
            options={'ordering': ['brand__name', 'variant_name'], 'verbose_name': 'Vehicle Variant', 'verbose_name_plural': 'Vehicle Variants'},
        ),
        migrations.AddField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 20, 16, 24, 33, 611335, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehiclevariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 20, 16, 24, 43, 751845, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclevariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='brand_images/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclevariant',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_variants', to='interactions.brand'),
        ),
        migrations.AlterField(
            model_name='vehiclevariant',
            name='variant_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclevariant',
            unique_together={('brand', 'variant_name')},
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='index.servicecenter')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-date_added'],
                'unique_together': {('phone', 'service_center')},
            },
        ),
        migrations.CreateModel(
            name='VehicleOnService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.PositiveIntegerField(help_text='Vehicle manufacturing year', validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2026)])),
                ('vehicle_number', models.CharField(max_length=20)),
                ('transport_type', models.CharField(choices=[('private', 'Private'), ('goods_transport', 'Goods Transport'), ('passenger_transport', 'Passenger Transport'), ('commercial', 'Commercial'), ('other', 'Other')], default='private', max_length=50)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_vehicles', to='interactions.customer')),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='index.servicecenter')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactions.vehiclevariant')),
            ],
            options={
                'verbose_name': 'Vehicle on Service',
                'verbose_name_plural': 'Vehicles on Service',
                'ordering': ['-date_added'],
                'unique_together': {('vehicle_number', 'service_center')},
            },
        ),
        migrations.CreateModel(
            name='ServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('service_date', models.DateField(default=django.utils.timezone.now)),
                ('service_type', models.CharField(choices=[('alignment', 'Wheel Alignment'), ('balancing', 'Wheel Balancing'), ('rotation', 'Wheel Rotation'), ('change', 'Wheel Change'), ('repair', 'Wheel Repair'), ('inspection', 'Wheel Inspection'), ('other', 'Other')], default='alignment', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional service details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('next_service_due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_services', to='interactions.customer')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_services', to=settings.AUTH_USER_MODEL)),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_entries', to='index.servicecenter')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_services', to='interactions.vehicleonservice')),
            ],
            options={
                'verbose_name': 'Service Entry',
                'verbose_name_plural': 'Service Entries',
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
