# Generated by Django 5.2.4 on 2025-08-25 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_alter_brand_options_alter_vehiclevariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleonservice',
            name='kilometer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
