# Generated by Django 5.2.4 on 2025-08-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_vehicleonservice_kilometer_alter_serviceentry_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleonservice',
            name='kilometer',
        ),
        migrations.AddField(
            model_name='serviceentry',
            name='kilometer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
