# Generated by Django 5.2.4 on 2025-09-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_remove_vehicleonservice_kilometer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceentry',
            name='next_kilometer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
