# Generated by Django 5.2.4 on 2026-02-14 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0005_serviceentry_next_kilometer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleonservice",
            name="vehicle_model",
            field=models.PositiveIntegerField(
                help_text="Vehicle manufacturing year",
                validators=[
                    django.core.validators.MinValueValidator(1980),
                    django.core.validators.MaxValueValidator(2027),
                ],
            ),
        ),
    ]
