# Generated by Django 5.2.4 on 2025-09-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_paymentplan_paymenttransaction_subscriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='sms_frequency_for_private_vehicles',
            field=models.IntegerField(default=3, help_text='Sms Frequency for Pvt vehicle Default at 3 months data in months'),
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='sms_frequency_for_transport_vehicles',
            field=models.IntegerField(default=3, help_text='Sms Frequency for Transport vehicle Default at 3 months data in months'),
        ),
    ]
