# Generated by Django 5.2.4 on 2025-09-09 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_servicecenter_sms_frequency_for_private_vehicles_and_more'),
        ('interactions', '0005_serviceentry_next_kilometer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('sms_type', models.CharField(choices=[('service_reminder', 'Service Reminder'), ('payment_reminder', 'Payment Reminder'), ('promotional', 'Promotional'), ('other', 'Other')], default='service_reminder', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='interactions.customer')),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='index.servicecenter')),
                ('service_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='interactions.serviceentry')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='interactions.vehicleonservice')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
