# Generated by Django 5.2.4 on 2026-02-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0008_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
